#baseURL = 'localhost'
baseURL = 'https://xycf2233.github.io'
title = '小羊炒饭'

theme = 'hugo-theme-reimu'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1

# 代码块
[markup.highlight]
guessSyntax = true
noClasses = false
